openapi: 3.1.0
info:
  title: The Dog API
  version: 1.3.9
  description: The Dog API provides various endpoints related to dog data.

servers:
  - url: https://api.thedogapi.com/v1

paths:
  /:
    get:
      operationId: getApiInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInfo'
          description: Returns basic information about The Dog API.
        default:
          description: An error occurred.
      summary: Returns basic information about The Dog API.

  /breeds:
    get:
      operationId: getBreeds
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Breed'
          description: Retrieve all dog breeds.
        default:
          description: An error occurred.
      summary: Retrieve all dog breeds.

  /categories:
    get:
      operationId: getCategories
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: Retrieve all categories.
        default:
          description: An error occurred.
      summary: Retrieve all categories.

  /images/{image_id}:
    get:
      operationId: getImageById
      parameters:
        - name: image_id
          in: path
          required: true
          description: The ID of the image to retrieve.
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DogImage'
          description: Retrieve a specific image by ID.
        default:
          description: An error occurred.
      summary: Retrieve a specific image by ID.

  /images/search:
    get:
      operationId: searchDogImages
      parameters:
        - name: format
          in: query
          description: Response format (json or src).
          schema:
            type: string
        - name: page
          in: query
          description: Integer - used for paginating through all the results.
          schema:
            type: integer
        - name: x-api-key
          in: header
          description: API Key for extended access.
          schema:
            type: string
        - name: size
          in: query
          description: The size of the image to return.
          schema:
            type: string
        - name: mime_types
          in: query
          description: Comma-delimited string of image types to return (gif, jpg, png).
          schema:
            type: string
        - name: category_ids
          in: query
          description: Comma-delimited string of integers, matching the IDs of the Categories to filter the search.
          schema:
            type: string
        - name: breed_ids
          in: query
          description: Comma-delimited string of integers, matching the IDs of the Breeds to filter the search.
          schema:
            type: string
        - name: order
          in: query
          description: The order to return results in.
          schema:
            type: string
        - name: limit
          in: query
          description: Integer - number of results to return.
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DogImage'
          description: Search for dog images.
        default:
          description: An error occurred.
      summary: Search for dog images.

components:
  schemas:
    ApiInfo:
      type: object
      properties:
        message:
          type: string
          description: A message providing additional information or feedback from The Dog API.
        version:
          type: string
          description: Version of The Dog API.

    Breed:
      type: object
      properties:
        bred_for:
          type: string
          description: Specify what the dog breed is bred for, such as hunting, herding, or companionship.
        breed_group:
          type: string
          description: Specify the group of dog breeds.
        height:
          type: object
          properties:
            imperial:
              type: string
              description: Height in imperial units.
            metric:
              type: string
              description: Height in metric units.
        id:
          type: number
          description: Unique identifier for each dog breed.
        life_span:
          type: string
          description: The average lifespan of the dog breed.
        name:
          type: string
          description: Name of the dog breed.
        origin:
          type: string
          description: The origin of the dog breed.
        reference_image_id:
          type: string
          description: Unique identifier of the reference image for the dog breed.
        temperament:
          type: string
          description: Temperament of the dog breed.
        weight:
          type: object
          properties:
            imperial:
              type: string
              description: Weight in imperial units.
            metric:
              type: string
              description: Weight in metric units.

    Category:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the category.
        name:
          type: string
          description: Name of the category.

    DogImage:
      type: object
      properties:
        breeds:
          type: array
          items:
            type: object
          description: Array of breed information associated with the image.
        height:
          type: integer
          description: Height of the image in pixels.
        id:
          type: string
          description: Unique identifier for the image.
        url:
          type: string
          description: URL of the image.
        width:
          type: integer
          description: Width of the image in pixels.

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Internal Server Error
          description: Error type or code.
        message:
          type: string
          example: An unexpected error occurred.
          description: Detailed error message.

  examples:
    getApiInfo:
      value:
        ReqExample: {}
        RespExample:
          message: "The Dog API"
          version: "1.3.9"
    
    getBreeds:
      value:
        ReqExample: {}
        RespExample:
          - bred_for: "Small rodent hunting, lapdog"
            breed_group: "Toy"
            height:
              imperial: "9 - 11.5"
              metric: "23 - 29"
            id: 1
            life_span: "10 - 12 years"
            name: "Affenpinscher"
            origin: "Germany, France"
            reference_image_id: "BJa4kxc4X"
            temperament: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving"
            weight:
              imperial: "6 - 13"
              metric: "3 - 6"
    
    getCategories:
      value:
        ReqExample: {}
        RespExample:
          - id: 5
            name: "boxes"
          - id: 15
            name: "clothes"
          - id: 1
            name: "hats"
    
    getImageById:
      value:
        ReqExample:
          image_id: "wRJ9Dwspqth"
        RespExample:
          id: "wRJ9Dwspqth"
          url: "https://cdn2.thedogapi.com/images/wRJ9Dwspqth.jpg"
          width: 1600
          height: 1062
          breeds:
            - weight:
                imperial: "10 - 17"
                metric: "5 - 8"
              height:
                imperial: "13 - 16"
                metric: "33 - 41"
              id: 133
              name: "Pomeranian"
              bred_for: "Companionship"
              breed_group: "Toy"
              life_span: "12 - 16 years"
              temperament: "Extroverted, Friendly, Sociable, Playful, Intelligent, Active"
              reference_image_id: "HJd0XecNX"
    
    searchDogImages:
      value:
        ReqExample:
          limit: 3
          breed_ids: 1
          order: "ASC"
        RespExample:
          - breeds:
              - weight:
                  imperial: "6 - 13"
                  metric: "3 - 6"
                height:
                  imperial: "9 - 11.5"
                  metric: "23 - 29"
                id: 1
                name: "Affenpinscher"
                bred_for: "Small rodent hunting, lapdog"
                breed_group: "Toy"
                life_span: "10 - 12 years"
                temperament: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving"
                reference_image_id: "BJa4kxc4X"
            id: "BJa4kxc4X"
            url: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg"
            width: 1600
            height: 1199 